# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.

title: sigruby00's Website
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal website. This is a start page built with Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sigruby00.github.io" # the base hostname & protocol for your site

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .git/
  - .gitignore
